version: '0.1.1'
services:
  postgres_db:
    build:
      context: pg_db/
      dockerfile: Dockerfile
    container_name: shop-pg-db-container
    env_file: 
      - f_api/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U users_admin -d marketplace"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
    expose:
      - "5432"
    #ports:
    #  - "5432:5432"
    networks:
      - docker-virtual-network
  fast_api:
    build:
      context: f_api/
      dockerfile: Dockerfile
    container_name: my-fast_api-container
    restart: always
    env_file: 
      - f_api/.env
    networks:
      - docker-virtual-network
    ports:
     - "8066:8066"
    depends_on:
      postgres_db:
        condition: service_healthy 
  
networks:
  docker-virtual-network:
